spring.application.name=iotbackend

spring.datasource.url=jdbc:postgresql://localhost:5432/iot_db
spring.datasource.username=postgres
spring.datasource.password=Duy10012004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#MAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongdangduy95@gmail.com
spring.mail.password=umpmtgjmhvziqqev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8087
