spring.application.name=iotbackend

jwt.secret=duongdangduyduyduongdangmysecreteypitbullduongdangduyduyduongdangmysecreteypitbull

#spring.datasource.url=jdbc:postgresql://localhost:5432/iot_db
#spring.datasource.username=postgres
#spring.datasource.password=Duy10012004
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

spring.datasource.username=postgres.dsyhuyybhrmcmpqyfteb
spring.datasource.password=Duy0393323936/

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple

#MAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongdangduy95@gmail.com
spring.mail.password=umpmtgjmhvziqqev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#MQTT
mqtt.host=ssl://1c96de2709a740a68e5b6d81365811b2.s1.eu.hivemq.cloud:8883
mqtt.username=duyduong
mqtt.password=Duy10012004/
mqtt.client-id=spring-backend001

server.port=8087
